### ISSUE TITLE
save weight of pix2pix-keras

### ISSUE THREAD

**Issue by shoutashi** [tjwei/GANotebooks#5]
Hi tjwei, 
Thank for your wonderful code. could you please tell me how to save weight of that pix2pix-keras jupyter notebook after finish training? Thank you in advance.

**Comment by tjwei** [comment]
You can use `netG.save(filepath)` to save the network and use `netG = keras.models.load_model(filepath)` to  load the model.

If you only want to save weights, then `netG.save_weights('netG.h5')` and then `netG.load_weights('netG.h5')` to load the weights back.

**Comment by shoutashi** [comment]
Hi tjwei,
Yeah, I can reuse the model. Thank you so much.
